version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        # Do not merge when it is marked work in progress (WIP)
        or:
          - must_exclude:
              regex: \[WIP\]|\bWIP\b|🚧
              message: This is work in progress. Do not merge yet.
          - must_exclude:
              regex: ^\[DONT-MERGE\]
              message: Do not merge this PR yet.
      - do: label
        must_exclude:
          regex: 'wip'
      - do: label
        must_exclude:
          regex: 'dont-merge'
      # If package.json is updated, so should yarn.lock
      - do: dependent
        changed:
          file: 'package.json'
          files: ['yarn.lock']
